name: Teste trigger Issues

on:
  issues: 
    types: [opened, edited, deleted]

jobs:
  teste-trigger-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Teste trigger issues
        run: echo "Uma issue foi aberta/editada/deletada"