name: Testando a regra do trigger Create

on:
  create

jobs:
  print-branch-or-tag-creation: #job name
    runs-on: ubuntu-latest

    steps:
      - name: Aviso sobre criação de branches ou tags
        run: echo "Uma nova Branch ou Tag foi criada no repositório"
  