name: Testando arquivos entre Jobs
# nome do workflow

on:
  workflow_dispatch
# on > push > branches> workflow será executado sempre que for dado um commit na branche main

jobs:
  baca_job_1:  
    runs-on: ubuntu-latest  
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release

      - name: Exibir mensagem
        run: echo "Estou fazendo o curso de Github Actions" > ${{ github.workspace }}/mensagem.txt 
        #forma de salvar o arquivo dentro do workspace do git para compartilhar entre os jobs

      - uses: actions/upload-artifact@v4 #action para fazer upload de arquivos
        with:
          name: strigus-upload #nome do diretorio
          path: ${{ github.workspace }}/mensagem.txt #caminho onde o diretório será salvo

  baca_job_2:  
    runs-on: ubuntu-latest
    needs: baca_job_1 #executa job_2 somente após execução do job_1  
    steps:
      - name: Conteudo diretorio
        run: ls -lha

      - uses: actions/download-artifact@v4 #action para download do arquivo criado pelo job anterior
        with:
          name: strigus-upload #nome do diretorio de origem do arquivo no workspace do git
          path: strigus-download #nome do diretorio de destino do arquivo dentro da maquina onde o job_2 esta rodando
      
      - name: Conteudo diretorio
        run: ls -lha && echo "conteudo diretorio strigus-download" && ls -lha ./strigus-download/

      - name: Move aquivo mensagem diretorio
        run: mv strigus-download/mensagem.txt . && rm -rf ./strigus-download
      
      - name: Conteudo diretorio
        run: ls -lha
      
      - name: Le conteudo do arquivo
        run: cat mensagem.txt
  # steps são os passos que serão executados dentro do workflow (cuidado com a identeção do run, pois deve estar no mesmo nivel do name)
      