name: Testando regra de protection rule


on:
    branch_protection_rule:
        types: [created, edited, deleted]

jobs:
    print-modification:
        runs-on: ubuntu-latest
        steps:

            - name: Avisa sobre modificações
              run: echo "Este workflow foi executado pois uma regra de Branch Protection foi alterada"



    