name: Chama Workflow Compartilhado

on:
    workflow_dispatch:
        inputs:
            nome-do-curso-enviado:
                required: true
                type: string

jobs:
    workflow-call:
        uses: ./.github/workflows/trigger-call.yml #essa 
        with:
            nome-do-curso-recebido: ${{ inputs.nome-do-curso-enviado}}