name: Desafio aula 1
    
on:
    workflow_dispatch:
        inputs:
            define_docker_image:
                description: 'Define docker image para execução'
                required: true
                default: alpine:latest
                type: string
jobs:
    #inicio da execução dos jobs
    bacaflow_1:
    #nome do job
        runs-on: ubuntu-latest
        #job rodando em um runner ubuntu

        steps:
              #primeiro step  verifica a versao do SO do runner
            - name: versao Ubuntu (runner)
              run: cat /etc/os-release
            
              #Segundo step sobe o container com a Imagem selecionada na execucao do workflow
            - name: Baixa imagem docker
              run: | #pipe server para quebrar a linha
                docker pull ${{ github.event.inputs.define_docker_image}}

            
              #Terceiro step executa o comando docker images para mostrar a imagem usada no container
            - name: Executa docker image
              run: docker images
            
              #Quarto step executa login no Docker Hub para usar o Docker Scout
            - name: Login no Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
              #Quinto step executa o Docker Scout e mostra as vulnerabilidades da imagem usada
            - uses: docker/scout-action@v1.18.2
              with:
                command: cves
                image: ${{ github.event.inputs.define_docker_image }}
                only-severities: critical,high
                summary: true

