name: Desafio aula 1
    
on:
    workflow_dispatch:
        inputs:
            docker_image:
                description: Imagem docker a ser executada
                required: true
                default: alpine:latest

jobs:
    #inicio da execução dos jobs
    bacaflow_1:
        #nome do job
        runs-on: ubuntu-latest
        #job rodando em um runner ubuntu

        steps:
        #primeiro step do job
            - name: versao Ubuntu (runner)
              run: cat /etc/os-release
            
            - name: Subir container em background
              run: |
                docker run -d --name alpine_teste \
                  ${{ github.event.inputs.docker_image }} \
                  sh -c "while true; do sleep 5; done"
            
            - name: Executa docker image
              run: docker images
            

