name: Primeiro Workflow curso Github Actions

on:
  push:
    branches:
      - main

jobs:
  bacaflow:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release

      - name: Exibir mensagem
        run: echo "Estou fazendo o curso de Github Actions"