name: Teste Trigger Call

on: 
    workflow_call:
        inputs:
            nome-do-curso-recebido:
                required: true
                type: string

jobs:
    nome-do-curso:
        runs-on: ubuntu-latest
        steps:
                - name: Informe o nome do curso
                  run: echo "O nome do seu curso é ${{ inputs.nome-do-curso-nome-do-curso-recebido}}"